#!perl

# DATE
# VERSION

use 5.010;
use strict;
use warnings;

use Perinci::CmdLine::Any;

Perinci::CmdLine::Any->new(
    url => '/SHARYANTO/TimeSheet/Parser/calc_hours_minutes',
)->run;

1;
# ABSTRACT:
# PODNAME:
