#!perl

# DATE
# VERSION

use 5.010;
use strict;
use warnings;

use Perinci::CmdLine;

Perinci::CmdLine->new(url => '/SHARYANTO/TimeSheet/Parser/fill_in_daily_totals')->run;

1;
# ABSTRACT:
# PODNAME:
